language: python
python:
  - 2.7
env:
  - FLASK_VERSION=0.9
  - FLASK_VERSION=0.10.1
  - FLASK_VERSION=0.11.1
install:
  - pip install -r requirements.txt
  - pip install -I Flask==$FLASK_VERSION
script:
  - py.test test_flask_redislite.py --pep8 flask_redislite.py -v --cov flask_redislite --cov-report term-missing
after_success: coveralls
matrix:
  include:
  - os: linux
    dist: trusty
    python: '2.7'
