language: python
python:
  - 2.7
install:
  - pip install -r requirements.txt
script:
  - python test_flask_redislite.py
after_success: coveralls
matrix:
  include:
  - os: linux
    dist: trusty
    python: '2.7'
